apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-configmap
  namespace: hackathon-ns
data:
  SPRING_R2DBC_URL: "r2dbc:postgresql://neondb_owner:npg_j3TvBXkeU0KH@ep-little-king-at4oe1qz-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

