apiVersion: v1
kind: Secret
metadata:
  name: hackathon-secret
  namespace: hackathon-ns
type: Opaque
data:
  SPRING_R2DBC_USERNAME: bmVvbmRiX293bmVy
  SPRING_R2DBC_PASSWORD: bnBnX2ozVHZCWGtlVTBLSA==
